# pygments_style lightbulb
# title_bg #7aa2f7
# title_fg #1f2335
# margin_bg #292e42
# margin_fg #545c7e
# filler_bg #1a1b26
# margin_filler_bg none

# removed_bg           #f7768e
# highlight_removed_bg #f7768e
# removed_margin_bg    #ffdce0

