theme ="tokyonight"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
true-color = true
auto-format = false
auto-save = false
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]



[keys.normal.space]
# l = [":sh kitty @ launch --type=os-window --cwd=current --env HX_SEND=${KITTY_WINDOW_ID} -- kitten @ send-text -m id:${HX_SEND} $(nnn -p -)"]
# l = [":sh kitty @ launch --type overlay --cwd current --env HX_SEND=${KITTY_WINDOW_ID} -- nnn -p -; kitten @ send-text --match id:3 'neat'"]
# k = [":pipe :o", ":sh kitten @ send-text --match id:3 --stdin"]
i = ":fmt" # Format current buffer

