theme ="tokyonight"

[editor]
line-number = "relative"
shell = ["zsh", "-c"]
true-color = true
# auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true

[editor.statusline]
right = ["version-control", "diagnostics", "selections", "position", "file-encoding"]

