prSections:
- title: My Pull Requests
  filters: is:open author:@me
  type: null
- title: Needs My Review
  filters: is:open review-requested:@me
  type: null
- title: Involved
  filters: is:open involves:@me -author:@me
  type: null
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Involved
  filters: is:open involves:@me -author:@me
repoPaths:
  ObieCRE/risk-management: ~/workspace/risk-management
repo:
  branchesRefetchIntervalSeconds: 30
  prsRefetchIntervalSeconds: 60
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  prApproveComment: LGTM
  issuesLimit: 20
  view: prs
  layout:
    prs:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 20
      author:
        width: 15
      authorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 15
    issues:
      updatedAt:
        width: 5
      createdAt:
        width: 5
      repo:
        width: 15
      creator:
        width: 10
      creatorIcon:
        hidden: false
      assignees:
        width: 20
        hidden: true
  refetchIntervalMinutes: 30
keybindings:
  universal: []
  issues: []
  prs:
    - key: P
      command: open $(heroku config:get DATABASE_URL --app obie-rm-review-pr-{{.PrNumber}})
    - key: b
      command: >
        cd {{.RepoPath}} && gh pr view {{.PrNumber}} --json statusCheckRollup --template \ '{{`{{range .statusCheckRollup}}{{if .state}}`}}
          {{`## {{.context}}`}} 
          {{`+ Started: **{{.startedAt}}**`}}
          {{`+ Status:  **{{.state}}** {{if (eq .state "SUCCESS")}}✅{{end}}{{if (eq .state "FAILURE")}}❌{{end}}{{if (eq .state "ERROR")}}❌{{end}}{{if (eq .state "PENDING")}}⏱️{{end}}`}}
          {{`+ [Details:]({{.targetUrl}})`}}
          {{`{{end}}{{end}}`}}' | glow -p -s tokyo-night -w 180
  branches: []
repoPaths: {}
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
      compact: false
pager:
  diff: ""
confirmQuit: false
showAuthorIcons: true
smartFilteringAtLaunch: true
